services:
  caddy:
    image: caddy:2.8-alpine
    container_name: vpinplay_caddy
    ports:
      - "8888:8888"
    restart: unless-stopped
    volumes:
      - ./Caddyfile.local-mac:/etc/caddy/Caddyfile:ro
      - ./www:/www:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  mongo_data:
  caddy_data:
  caddy_config: